/**
 * testFixtures.ts
 *
 * Synthetic scanner test fixtures for the Developer Test Lab.
 * Each fixture defines the expected extraction output for a synthetic document
 * generated by `generateSyntheticDocument()`.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type FixtureCategory = 'Banking' | 'Income' | 'Debts' | 'Investments' | 'Bills' | 'File Types';
export type ToleranceType = 'dollar' | 'percentage' | 'hours' | 'text' | 'date';
export type DestSection = 'assets' | 'debts' | 'bills' | 'paystubs' | 'skip';

export interface ExpectedField {
  value: string | number;
  tolerance?: number;
  toleranceType?: ToleranceType;
}

export interface ScannerTestFixture {
  id: string;
  name: string;
  category: FixtureCategory;
  /** MIME type for the generated file */
  mimeType: 'image/jpeg' | 'image/png';
  /** Filename extension (may differ from mimeType for File Types category) */
  fileExtension: string;
  expectedDocType: string;
  expectedInstitution?: string;
  /** Fields expected in scan result — key matches API field names */
  expectedFields: Record<string, ExpectedField>;
  expectedDestination: DestSection;
  /** If true, also exercise buildUpdatePlan + applyUpdatePlan */
  fullFlowCheck?: boolean;
}

// ─── Canvas document generator ────────────────────────────────────────────────

export interface DocSpec {
  institution: string;
  docType: string;
  accountNumber: string;
  statementDate: string;
  /** Display rows: label → display value */
  rows: Array<[string, string]>;
}

/** Build the display rows from fixture expected fields for the canvas renderer. */
function buildDocSpec(fixture: ScannerTestFixture): DocSpec {
  const labelMap: Record<string, string> = {
    currentBalance:    'Current Balance',
    availableBalance:  'Available Balance',
    closingBalance:    'Closing Balance',
    accountType:       'Account Type',
    grossPay:          'Gross Pay',
    netPay:            'Net Pay',
    regularHours:      'Regular Hours',
    overtimeHours:     'Overtime Hours',
    taxes:             'Taxes Withheld',
    deductions:        'Deductions',
    perDiem:           'Per Diem',
    employer:          'Employer',
    balance:           'Account Balance',
    currentBalance2:   'Current Balance',
    principalBalance:  'Principal Balance',
    statementBalance:  'Statement Balance',
    interestRate:      'Annual Percentage Rate',
    apr:               'APR',
    minimumPayment:    'Minimum Payment',
    monthlyPayment:    'Monthly Payment',
    amountDue:         'Amount Due',
    dueDate:           'Due Date',
    provider:          'Provider',
    totalValue:        'Total Account Value',
    vestedBalance:     'Vested Balance',
    planName:          'Plan Name',
    employer401k:      'Employer',
    interestEarned:    'Interest Earned',
    maturityDate:      'Maturity Date',
    creditLimit:       'Credit Limit',
    paymentDue:        'Payment Due Date',
    loanAmount:        'Original Loan Amount',
  };

  const rows: Array<[string, string]> = [];
  for (const [key, ef] of Object.entries(fixture.expectedFields)) {
    const label = labelMap[key] ?? key.replace(/([A-Z])/g, ' $1').trim();
    const v = ef.value;
    let display: string;
    if (typeof v === 'number') {
      const tt = ef.toleranceType ?? 'dollar';
      if (tt === 'dollar') display = `$${v.toFixed(2)}`;
      else if (tt === 'percentage') display = `${v}%`;
      else if (tt === 'hours') display = `${v} hrs`;
      else display = String(v);
    } else {
      display = v;
    }
    rows.push([label, display]);
  }
  return {
    institution: fixture.expectedInstitution ?? 'Financial Institution',
    docType: fixture.expectedDocType,
    accountNumber: '****' + (4000 + parseInt(fixture.id.replace(/\D/g, '').slice(0, 4) || '1', 10) % 9000).toString(),
    statementDate: 'July 1, 2026',
    rows,
  };
}

/**
 * Generate a synthetic financial document as a File using the HTML5 Canvas API.
 * The output is a JPEG or PNG image with enough text for the Vision API to
 * classify and extract fields.
 */
export async function generateSyntheticDocument(
  fixture: ScannerTestFixture,
  spec?: Partial<DocSpec>,
): Promise<File> {
  const canvas = document.createElement('canvas');
  canvas.width = 820;
  canvas.height = 620;
  const ctx = canvas.getContext('2d')!;
  const ds = { ...buildDocSpec(fixture), ...spec };

  // White background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Header bar
  ctx.fillStyle = '#0d2d4e';
  ctx.fillRect(0, 0, canvas.width, 85);

  // Institution name
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 22px Arial, sans-serif';
  ctx.fillText(ds.institution, 28, 38);

  // Document type subtitle
  ctx.font = '15px Arial, sans-serif';
  ctx.fillStyle = '#a8c8e8';
  ctx.fillText(ds.docType.toUpperCase(), 28, 65);

  // Thin accent line
  ctx.fillStyle = '#1e7bc4';
  ctx.fillRect(0, 85, canvas.width, 4);

  // Account info row
  ctx.fillStyle = '#555555';
  ctx.font = '13px Arial, sans-serif';
  ctx.fillText(`Account Number: ${ds.accountNumber}`, 28, 115);
  ctx.fillText(`Statement Date: ${ds.statementDate}`, 420, 115);

  // Divider
  ctx.strokeStyle = '#e0e0e0';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(28, 130);
  ctx.lineTo(canvas.width - 28, 130);
  ctx.stroke();

  // Field rows
  let y = 162;
  const COL_LABEL = 28;
  const COL_VALUE = 380;

  for (const [label, value] of ds.rows) {
    if (y > canvas.height - 60) break;

    // Zebra stripe
    if ((ds.rows.indexOf([label, value]) + 0) % 2 === 0) {
      ctx.fillStyle = '#f8f9fa';
      ctx.fillRect(0, y - 18, canvas.width, 28);
    }

    ctx.fillStyle = '#666666';
    ctx.font = '13px Arial, sans-serif';
    ctx.fillText(label + ':', COL_LABEL, y);

    ctx.fillStyle = '#111111';
    ctx.font = 'bold 13px Arial, sans-serif';
    ctx.fillText(value, COL_VALUE, y);

    y += 30;
  }

  // Footer
  ctx.fillStyle = '#999999';
  ctx.font = '11px Arial, sans-serif';
  ctx.fillText('CONFIDENTIAL — For authorized account holder use only', 28, canvas.height - 18);

  // Watermark with doc type for AI clarity
  ctx.save();
  ctx.globalAlpha = 0.04;
  ctx.font = 'bold 48px Arial, sans-serif';
  ctx.fillStyle = '#000000';
  ctx.translate(canvas.width / 2, canvas.height / 2);
  ctx.rotate(-0.3);
  ctx.fillText(ds.docType, -200, 0);
  ctx.restore();

  const mimeType = fixture.mimeType;
  const ext = fixture.fileExtension;
  const filename = `${fixture.id.replace(/_/g, '-')}-statement.${ext}`;

  return new Promise<File>((resolve, reject) => {
    canvas.toBlob(
      blob => {
        if (!blob) return reject(new Error('Canvas toBlob returned null'));
        resolve(new File([blob], filename, { type: mimeType }));
      },
      mimeType,
      0.92,
    );
  });
}

// ─── Fixture definitions ──────────────────────────────────────────────────────

export const FIXTURES: ScannerTestFixture[] = [
  // ═══════════════════════════════ Banking (7) ════════════════════════════════
  {
    id: 'ttcu_checking',
    name: 'TTCU Federal Credit Union — Checking',
    category: 'Banking',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Checking Account',
    expectedInstitution: 'TTCU Federal Credit Union',
    expectedFields: {
      currentBalance:   { value: 2450.00, toleranceType: 'dollar', tolerance: 1.00 },
      availableBalance: { value: 2430.00, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'assets',
    fullFlowCheck: true,
  },
  {
    id: 'chase_savings',
    name: 'Chase — Savings Account',
    category: 'Banking',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Savings Account',
    expectedInstitution: 'Chase',
    expectedFields: {
      currentBalance:  { value: 8500.00, toleranceType: 'dollar', tolerance: 1.00 },
      interestEarned:  { value: 12.50,   toleranceType: 'dollar', tolerance: 0.10 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'ally_hysa',
    name: 'Ally Bank — High-Yield Savings',
    category: 'Banking',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'High-Yield Savings',
    expectedInstitution: 'Ally Bank',
    expectedFields: {
      currentBalance: { value: 15000.00, toleranceType: 'dollar', tolerance: 1.00 },
      apr:            { value: 4.50, toleranceType: 'percentage', tolerance: 0.10 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'navy_federal_mm',
    name: 'Navy Federal — Money Market Account',
    category: 'Banking',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Money Market Account',
    expectedInstitution: 'Navy Federal Credit Union',
    expectedFields: {
      currentBalance: { value: 25000.00, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'marcus_cd',
    name: 'Marcus by Goldman Sachs — Certificate of Deposit',
    category: 'Banking',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Certificate of Deposit',
    expectedInstitution: 'Marcus by Goldman Sachs',
    expectedFields: {
      currentBalance: { value: 10000.00, toleranceType: 'dollar', tolerance: 1.00 },
      apr:            { value: 5.00, toleranceType: 'percentage', tolerance: 0.10 },
      maturityDate:   { value: '2027-01-15', toleranceType: 'date' },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'sofi_cash',
    name: 'SoFi — Cash Management Account',
    category: 'Banking',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Cash Management Account',
    expectedInstitution: 'SoFi',
    expectedFields: {
      currentBalance: { value: 3750.00, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'bofa_statement',
    name: 'Bank of America — Bank Statement',
    category: 'Banking',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Bank Statement',
    expectedInstitution: 'Bank of America',
    expectedFields: {
      closingBalance:  { value: 4200.00, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'assets',
  },

  // ═══════════════════════════════ Income (5) ═════════════════════════════════
  {
    id: 'union_paystub',
    name: 'Union Plumber — Regular + Overtime Paystub',
    category: 'Income',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Paystub',
    expectedInstitution: undefined,
    expectedFields: {
      grossPay:      { value: 1854.00, toleranceType: 'dollar', tolerance: 2.00 },
      netPay:        { value: 1384.00, toleranceType: 'dollar', tolerance: 2.00 },
      regularHours:  { value: 40, toleranceType: 'hours', tolerance: 0.5 },
      overtimeHours: { value: 8,  toleranceType: 'hours', tolerance: 0.5 },
      taxes:         { value: 350.00, toleranceType: 'dollar', tolerance: 5.00 },
    },
    expectedDestination: 'paystubs',
  },
  {
    id: 'hourly_paystub',
    name: 'Electrician — Hourly Paystub',
    category: 'Income',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Paystub',
    expectedFields: {
      grossPay:     { value: 1560.00, toleranceType: 'dollar', tolerance: 2.00 },
      netPay:       { value: 1185.00, toleranceType: 'dollar', tolerance: 2.00 },
      regularHours: { value: 40, toleranceType: 'hours', tolerance: 0.5 },
    },
    expectedDestination: 'paystubs',
  },
  {
    id: 'perdiem_paystub',
    name: 'Pipeline Worker — Per Diem Paystub',
    category: 'Income',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Paystub',
    expectedFields: {
      grossPay:      { value: 2100.00, toleranceType: 'dollar', tolerance: 5.00 },
      netPay:        { value: 1650.00, toleranceType: 'dollar', tolerance: 5.00 },
      regularHours:  { value: 40, toleranceType: 'hours', tolerance: 0.5 },
      perDiem:       { value: 200.00, toleranceType: 'dollar', tolerance: 5.00 },
    },
    expectedDestination: 'paystubs',
  },
  {
    id: 'biweekly_paystub',
    name: 'HVAC Tech — Bi-Weekly Paystub',
    category: 'Income',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Paystub',
    expectedFields: {
      grossPay:      { value: 2950.00, toleranceType: 'dollar', tolerance: 5.00 },
      netPay:        { value: 2240.00, toleranceType: 'dollar', tolerance: 5.00 },
      regularHours:  { value: 80, toleranceType: 'hours', tolerance: 1.0 },
    },
    expectedDestination: 'paystubs',
  },
  {
    id: 'doubletime_paystub',
    name: 'Ironworker — Double-Time Paystub',
    category: 'Income',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Paystub',
    expectedFields: {
      grossPay:         { value: 2600.00, toleranceType: 'dollar', tolerance: 5.00 },
      netPay:           { value: 1940.00, toleranceType: 'dollar', tolerance: 5.00 },
      regularHours:     { value: 40, toleranceType: 'hours', tolerance: 0.5 },
      overtimeHours:    { value: 4, toleranceType: 'hours', tolerance: 0.5 },
      doubleTimeHours:  { value: 4, toleranceType: 'hours', tolerance: 0.5 },
    },
    expectedDestination: 'paystubs',
  },

  // ═══════════════════════════════ Debts (8) ══════════════════════════════════
  {
    id: 'chase_cc',
    name: 'Chase — Credit Card',
    category: 'Debts',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Credit Card',
    expectedInstitution: 'Chase',
    expectedFields: {
      statementBalance: { value: 3200.00, toleranceType: 'dollar', tolerance: 1.00 },
      minimumPayment:   { value: 110.00,  toleranceType: 'dollar', tolerance: 1.00 },
      apr:              { value: 19.99, toleranceType: 'percentage', tolerance: 0.10 },
      creditLimit:      { value: 8000.00, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'debts',
  },
  {
    id: 'capital_one_cc_stmt',
    name: 'Capital One — Credit Card Statement',
    category: 'Debts',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Credit Card Statement',
    expectedInstitution: 'Capital One',
    expectedFields: {
      statementBalance: { value: 1450.00, toleranceType: 'dollar', tolerance: 1.00 },
      minimumPayment:   { value: 35.00,   toleranceType: 'dollar', tolerance: 1.00 },
      apr:              { value: 24.99, toleranceType: 'percentage', tolerance: 0.10 },
    },
    expectedDestination: 'debts',
  },
  {
    id: 'wells_loc',
    name: 'Wells Fargo — Line of Credit',
    category: 'Debts',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Line of Credit',
    expectedInstitution: 'Wells Fargo',
    expectedFields: {
      currentBalance:  { value: 5500.00, toleranceType: 'dollar', tolerance: 1.00 },
      minimumPayment:  { value: 120.00,  toleranceType: 'dollar', tolerance: 1.00 },
      apr:             { value: 12.50, toleranceType: 'percentage', tolerance: 0.20 },
    },
    expectedDestination: 'debts',
  },
  {
    id: 'toyota_auto',
    name: 'Toyota Financial — Auto Loan',
    category: 'Debts',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Auto Loan',
    expectedInstitution: 'Toyota Financial Services',
    expectedFields: {
      principalBalance: { value: 24500.00, toleranceType: 'dollar', tolerance: 5.00 },
      monthlyPayment:   { value: 480.00,   toleranceType: 'dollar', tolerance: 2.00 },
      interestRate:     { value: 5.50, toleranceType: 'percentage', tolerance: 0.10 },
    },
    expectedDestination: 'debts',
  },
  {
    id: 'discover_personal',
    name: 'Discover — Personal Loan',
    category: 'Debts',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Personal Loan',
    expectedInstitution: 'Discover Bank',
    expectedFields: {
      principalBalance: { value: 8000.00, toleranceType: 'dollar', tolerance: 5.00 },
      monthlyPayment:   { value: 220.00,  toleranceType: 'dollar', tolerance: 2.00 },
      interestRate:     { value: 11.99, toleranceType: 'percentage', tolerance: 0.10 },
    },
    expectedDestination: 'debts',
  },
  {
    id: 'rocket_mortgage',
    name: 'Rocket Mortgage — Home Mortgage',
    category: 'Debts',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Mortgage',
    expectedInstitution: 'Rocket Mortgage',
    expectedFields: {
      principalBalance: { value: 185000.00, toleranceType: 'dollar', tolerance: 10.00 },
      monthlyPayment:   { value: 1250.00,   toleranceType: 'dollar', tolerance: 5.00 },
      interestRate:     { value: 6.75, toleranceType: 'percentage', tolerance: 0.10 },
    },
    expectedDestination: 'debts',
  },
  {
    id: 'figure_heloc',
    name: 'Figure — Home Equity Line of Credit',
    category: 'Debts',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'HELOC',
    expectedFields: {
      currentBalance:  { value: 12000.00, toleranceType: 'dollar', tolerance: 5.00 },
      minimumPayment:  { value: 180.00,   toleranceType: 'dollar', tolerance: 2.00 },
      apr:             { value: 8.75, toleranceType: 'percentage', tolerance: 0.20 },
    },
    expectedDestination: 'debts',
  },
  {
    id: 'navient_student',
    name: 'Navient — Student Loan',
    category: 'Debts',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Student Loan',
    expectedInstitution: 'Navient',
    expectedFields: {
      principalBalance: { value: 28500.00, toleranceType: 'dollar', tolerance: 5.00 },
      monthlyPayment:   { value: 295.00,   toleranceType: 'dollar', tolerance: 2.00 },
      interestRate:     { value: 5.05, toleranceType: 'percentage', tolerance: 0.10 },
    },
    expectedDestination: 'debts',
  },

  // ═══════════════════════════════ Investments (11) ═══════════════════════════
  {
    id: 'fidelity_brokerage',
    name: 'Fidelity — Brokerage Account',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Brokerage Account',
    expectedInstitution: 'Fidelity',
    expectedFields: {
      totalValue: { value: 42000.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'ibkr_margin',
    name: 'Interactive Brokers — Margin Account',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Margin Account',
    expectedInstitution: 'Interactive Brokers',
    expectedFields: {
      totalValue: { value: 18500.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'betterment_robo',
    name: 'Betterment — Robo-Adviser Account',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Robo-Adviser Account',
    expectedInstitution: 'Betterment',
    expectedFields: {
      totalValue: { value: 9200.00, toleranceType: 'dollar', tolerance: 5.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'fidelity_espp',
    name: 'Fidelity — Employee Stock Plan',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Employee Stock Plan',
    expectedInstitution: 'Fidelity',
    expectedFields: {
      totalValue: { value: 6800.00, toleranceType: 'dollar', tolerance: 5.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'vanguard_401k',
    name: 'Vanguard — 401(k)',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: '401(k)',
    expectedInstitution: 'Vanguard',
    expectedFields: {
      currentBalance: { value: 58000.00, toleranceType: 'dollar', tolerance: 10.00 },
      vestedBalance:  { value: 52000.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'fidelity_roth401k',
    name: 'Fidelity — Roth 401(k)',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Roth 401(k)',
    expectedInstitution: 'Fidelity',
    expectedFields: {
      currentBalance: { value: 22000.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'empower_403b',
    name: 'Empower — 403(b)',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: '403(b)',
    expectedInstitution: 'Empower',
    expectedFields: {
      currentBalance: { value: 34000.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'voya_457b',
    name: 'Voya Financial — 457(b)',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: '457(b)',
    expectedInstitution: 'Voya Financial',
    expectedFields: {
      currentBalance: { value: 19500.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'vanguard_ira',
    name: 'Vanguard — Traditional IRA',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Traditional IRA',
    expectedInstitution: 'Vanguard',
    expectedFields: {
      currentBalance: { value: 47000.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'fidelity_roth_ira',
    name: 'Fidelity — Roth IRA',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Roth IRA',
    expectedInstitution: 'Fidelity',
    expectedFields: {
      currentBalance: { value: 31000.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'schwab_sep_ira',
    name: 'Charles Schwab — SEP IRA',
    category: 'Investments',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'SEP IRA',
    expectedInstitution: 'Charles Schwab',
    expectedFields: {
      currentBalance: { value: 84000.00, toleranceType: 'dollar', tolerance: 10.00 },
    },
    expectedDestination: 'assets',
  },

  // ═══════════════════════════════ Bills (11) ══════════════════════════════════
  {
    id: 'pso_electric',
    name: 'PSO — Electric Bill',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Utility Bill',
    expectedInstitution: 'PSO',
    expectedFields: {
      amountDue: { value: 127.45, toleranceType: 'dollar', tolerance: 0.50 },
      dueDate:   { value: 20, toleranceType: 'text' },
    },
    expectedDestination: 'bills',
    fullFlowCheck: true,
  },
  {
    id: 'att_phone',
    name: 'AT&T — Phone Bill',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Monthly Bill',
    expectedInstitution: 'AT&T',
    expectedFields: {
      amountDue: { value: 95.00, toleranceType: 'dollar', tolerance: 0.50 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'cox_internet',
    name: 'Cox — Internet Bill',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Monthly Bill',
    expectedInstitution: 'Cox Communications',
    expectedFields: {
      amountDue: { value: 85.00, toleranceType: 'dollar', tolerance: 0.50 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'ong_gas',
    name: 'ONG — Natural Gas Bill',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Utility Bill',
    expectedInstitution: 'ONG',
    expectedFields: {
      amountDue: { value: 68.30, toleranceType: 'dollar', tolerance: 0.50 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'city_water',
    name: 'City — Water Bill',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Utility Bill',
    expectedFields: {
      amountDue: { value: 42.15, toleranceType: 'dollar', tolerance: 0.50 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'netflix',
    name: 'Netflix — Streaming Subscription',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Monthly Bill',
    expectedInstitution: 'Netflix',
    expectedFields: {
      amountDue: { value: 22.99, toleranceType: 'dollar', tolerance: 0.10 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'spotify',
    name: 'Spotify — Music Subscription',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Monthly Bill',
    expectedInstitution: 'Spotify',
    expectedFields: {
      amountDue: { value: 11.99, toleranceType: 'dollar', tolerance: 0.10 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'state_farm',
    name: 'State Farm — Home Insurance',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Monthly Bill',
    expectedInstitution: 'State Farm',
    expectedFields: {
      amountDue: { value: 145.00, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'progressive_auto',
    name: 'Progressive — Auto Insurance',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Monthly Bill',
    expectedInstitution: 'Progressive',
    expectedFields: {
      amountDue: { value: 112.50, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'hoa_fee',
    name: 'HOA — Monthly Dues',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Monthly Bill',
    expectedFields: {
      amountDue: { value: 200.00, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'geico_auto',
    name: 'GEICO — Auto Insurance',
    category: 'Bills',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Monthly Bill',
    expectedInstitution: 'GEICO',
    expectedFields: {
      amountDue: { value: 98.75, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'bills',
  },

  // ═══════════════════════════════ File Types (8) ══════════════════════════════
  {
    id: 'ft_checking_jpeg',
    name: 'File Type: JPEG — Checking Account',
    category: 'File Types',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Checking Account',
    expectedFields: {
      currentBalance: { value: 3100.00, toleranceType: 'dollar', tolerance: 2.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'ft_checking_png',
    name: 'File Type: PNG — Checking Account',
    category: 'File Types',
    mimeType: 'image/png',
    fileExtension: 'png',
    expectedDocType: 'Checking Account',
    expectedFields: {
      currentBalance: { value: 3100.00, toleranceType: 'dollar', tolerance: 2.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'ft_savings_jpeg',
    name: 'File Type: JPEG — Savings Account',
    category: 'File Types',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Savings Account',
    expectedFields: {
      currentBalance: { value: 6400.00, toleranceType: 'dollar', tolerance: 2.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'ft_savings_png',
    name: 'File Type: PNG — Savings Account',
    category: 'File Types',
    mimeType: 'image/png',
    fileExtension: 'png',
    expectedDocType: 'Savings Account',
    expectedFields: {
      currentBalance: { value: 6400.00, toleranceType: 'dollar', tolerance: 2.00 },
    },
    expectedDestination: 'assets',
  },
  {
    id: 'ft_electric_jpeg',
    name: 'File Type: JPEG — Electric Bill',
    category: 'File Types',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Utility Bill',
    expectedFields: {
      amountDue: { value: 89.50, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'ft_electric_png',
    name: 'File Type: PNG — Electric Bill',
    category: 'File Types',
    mimeType: 'image/png',
    fileExtension: 'png',
    expectedDocType: 'Utility Bill',
    expectedFields: {
      amountDue: { value: 89.50, toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'bills',
  },
  {
    id: 'ft_paystub_jpeg',
    name: 'File Type: JPEG — Paystub',
    category: 'File Types',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Paystub',
    expectedFields: {
      grossPay: { value: 1720.00, toleranceType: 'dollar', tolerance: 5.00 },
      netPay:   { value: 1310.00, toleranceType: 'dollar', tolerance: 5.00 },
    },
    expectedDestination: 'paystubs',
  },
  {
    id: 'ft_cc_jpeg',
    name: 'File Type: JPEG — Credit Card',
    category: 'File Types',
    mimeType: 'image/jpeg',
    fileExtension: 'jpg',
    expectedDocType: 'Credit Card',
    expectedFields: {
      statementBalance: { value: 2150.00, toleranceType: 'dollar', tolerance: 2.00 },
      minimumPayment:   { value: 55.00,   toleranceType: 'dollar', tolerance: 1.00 },
    },
    expectedDestination: 'debts',
  },
];

/** Convenience accessor: all unique categories in fixture order */
export const FIXTURE_CATEGORIES: FixtureCategory[] = [
  'Banking', 'Income', 'Debts', 'Investments', 'Bills', 'File Types',
];

/** Look up a fixture by id */
export function getFixture(id: string): ScannerTestFixture | undefined {
  return FIXTURES.find(f => f.id === id);
}
